### ISSUE TITLE
Submission to Chrome Extension Store

### ISSUE THREAD

**Issue by Murmur** [karl-rousseau/HybridTvViewer#1]
Do you have any time estimate of the Chrome Extension Store submission for this plugin?
I have downloaded files and installed from the local disk but Chrome popups an annoying "developer mode extension" message each time Chrome is run.

**Comment by karl-rousseau** [comment]
After digging such way, I found that Google is now making extension publishing not free and a fee is asked every year (for a developer account ... and they must have been inspired by Apple's marketing way). This is not a lot (5$ per year) but this is so annoying (it needs your true bank account information). So I will better go for Opera's browser which is now using Chromium's engine (compliant with Chrome extension API) and where extensions can be published for free on their store. I will do a publishing in 2 weeks as I will be on vacation with plenty of time for testing. I will also add more features.

**Comment by karl-rousseau** [comment]
The extension has been published to OPERA store today and its internal review is still ongoing.
I have put the extension URL inside the markdown README.
Enjoy

**Comment by karl-rousseau** [comment]
The publishing is stuck and I can't unlock it. I suggest to add this extension manually as described in the wiki section.
