### ISSUE TITLE
HbbTV page gets downloaded on Chrome 72

### ISSUE THREAD

**Issue by MatLeRock** [karl-rousseau/HybridTvViewer#10]
When i try to open a HbbTV-Page on Chrome (V72.0.3626.119, Mac 10.14.3) the page wont show :( Instead it is getting downloaded. It is probably some MIME-Type issue.

The app sends following header:
Content-Type: application/vnd.hbbtv.xhtml+xml; charset=UTF-8

Following Metadata is set:
`<!DOCTYPE html PUBLIC "-//HbbTV//1.1.1//EN" "http://www.hbbtv.org/dtd/HbbTV-1.1.1.dtd">`
...
`<meta http-equiv="content-type" content="application/vnd.hbbtv.xhtml+xml; charset=UTF-8"/>` 

Any idea?

**Comment by karl-rousseau** [comment]
Thank you for the info and you are right, Google has recently changed things in the used API -> https://developer.chrome.com/extensions/webRequest
I am investigating the issue and hope to fix it as the page detection is still working but the header overloading isn't.
Btw the same code is still working on Firefox.

**Comment by karl-rousseau** [comment]
Just to let you know that I have done some tests and I can reproduce this issue on various browser versions & platforms. It is not easy to find the version when this **regression** appeared and I hope Google will find it quickly as I open an issue on their site with a _test case example_.

See: https://bugs.chromium.org/p/chromium/issues/detail?id=945310&q=component%3APlatform%3EExtensions

**Comment by karl-rousseau** [comment]
Google has confirm this strange issue and gave an undocumented option.
This fix (only for Chrome and Chromium) is now integrated into current master branch (that will be tagged 0.6 in next release with more code to come)

Enjoy

**Comment by MatLeRock** [comment]
Great news! Thanks a lot!
